# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

defaults:
  &defaults
  docker:
    - image: circleci/node:14.15.4

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: 
          name: Installing dependencies
          command: npm install
      - run:
          name: Running some tests
          command: npm test

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-and-test:
    jobs:
      - test