# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2

jobs:
  test:
    docker:
      - image: circleci/node:14.15.4

    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: npm install
      - run:
          name: Running some tests
          command: npm test
  circleci-faster-tests:
    docker:
      - image: circleci/node:14.15.4
    parallelism: 2
    steps:
      - checkout
      - run: "npm install"
      - run: "npm test $(circleci tests glob tests/**/test_*.js,.jsx,.ts,.tsx | circleci tests split)"

workflows:
  version: 2
  build-and-test:
    jobs:
      - test
      - circleci-faster-tests
